{{- if .Values.monitor.ingress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "particular.monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "particular.monitor.labels" . | nindent 4 }}
  {{- with .Values.monitor.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.monitor.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.monitor.ingress.tls }}
  tls:
    {{- range .Values.monitor.ingress.tls }}
    - hosts: 
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "particular.monitor.fullname" . }}
              port:
                name: api
{{- end -}}