{{- if .Values.monitor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "particular.monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "particular.monitor.labels" . | nindent 4 }}
  {{- with .Values.monitor.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.monitor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.monitor.serviceAccount.automount }}
{{- end -}}
