{{- if .Values.audit.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "particular.audit.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "particular.audit.labels" . | nindent 4 }}
  {{- with .Values.audit.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.audit.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.audit.serviceAccount.automount }}
{{- end -}}
