apiVersion: v1
kind: Service
metadata:
  name: {{ include "particular.error.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "particular.error.labels" $ | nindent 4 }}
  {{- with $.Values.error.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.error.service.type }}
  ports:
    - name: api
      port: {{ $.Values.error.service.port }}
      protocol: TCP
      targetPort: 33333
  selector:
    {{- include "particular.error.selectorLabels" $ | nindent 4 }}