{{- if .Values.error.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "particular.error.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "particular.error.labels" . | nindent 4 }}
  {{- with .Values.error.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.error.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.error.serviceAccount.automount }}
{{- end -}}
