apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:
  name: example-ingress
  namespace: particular-platform-example
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
spec:
  defaultBackend:
    service:
      name: servicepulse-service
      port:
        name: frontend
  rules:
  - http:
      paths:
      - path: /ravendb/error
        pathType: Prefix
        backend:
          service:
            name: servicecontrol-error-service
            port:
              name: ravendb-http
      - path: /ravendb/audit
        pathType: Prefix
        backend:
          service:
            name: servicecontrol-audit-service
            port:
              name: ravendb-http
      - path: /rabbitmq
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              name: management