apiVersion: v1
kind: Service
metadata:
  name: servicecontrol-error-service
  namespace: particular-platform-example
  labels:
    app: particular-servicecontrol-error
spec:
  clusterIP: None
  ports:
  - name: error-http-api
    port: 33333
    protocol: TCP
    targetPort: 33333
  - name: ravendb-error-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: ravendb-error-snmp
    port: 161
    protocol: TCP
    targetPort: 161
  selector:
    app: particular-servicecontrol-error
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: error-db-files
  namespace: particular-platform-example
  labels:
    type: local
spec:
  storageClassName: error-db-local
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ "ReadWriteOnce"]
  capacity:
    storage: 10Gi
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/error-db-files"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: servicecontrol-error-statefulset
  namespace: particular-platform-example  
spec:
  serviceName: servicecontrol-error-service
  replicas: 1
  selector:
    matchLabels:
      app: particular-servicecontrol-error
  updateStrategy:
    type: OnDelete
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
  volumeClaimTemplates:
  - metadata:
      name: error-db-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        app: particular-servicecontrol-error
    spec:
      containers:
        - name: servicecontrol-error
          image: particular/servicecontrol:latest
          imagePullPolicy: Always
          ports:
          - name: error-http-api
            containerPort: 33333
            protocol: TCP
          env:
            - name: TRANSPORTTYPE
              valueFrom:
                configMapKeyRef:
                  name: transport-config 
                  key: TRANSPORTTYPE
            - name: CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: transport-config
                  key: CONNECTIONSTRING
            - name: RAVENDB_CONNECTIONSTRING
              value: http://localhost:8080
            - name: SERVICECONTROL_REMOTEINSTANCES
              value: '[{"api_uri":"http://servicecontrol-audit-service:44444/api"}]'
      initContainers:
        - name: servicecontrol-error-db
          image: particular/servicecontrol-ravendb:latest
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
          - name: ravendb-http-api
            containerPort: 8080
            protocol: TCP
          - name: ravendb-snmp
            containerPort: 161
            protocol: TCP
          volumeMounts:
          - name: error-db-data
            mountPath: /opt/RavenDB/Server/RavenData
        - name: wait-for-ravendb
          image: curlimages/curl:latest
          command: ['curl', '-o', 'ping.json', 'http://localhost:8080/admin/debug/node/ping']
        - name: init-servicecontrol-error
          image: particular/servicecontrol:latest
          args: ['--setup']
          env:
            - name: TRANSPORTTYPE
              valueFrom:
                configMapKeyRef:
                  name: transport-config 
                  key: TRANSPORTTYPE
            - name: CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: transport-config 
                  key: CONNECTIONSTRING
            - name: RAVENDB_CONNECTIONSTRING
              value: http://localhost:8080